development:
  AUTH_SECRET: blah!
  GOOGLE_CLIENT_ID: 586067862296-pttgljei109ujalg8kumqiepop4tdo2a.apps.googleusercontent.com
  GOOGLE_CLIENT_SECRET: ug7mg7n_RUG8wxQIz-pRHcZz
  FACEBOOK_CLIENT_ID: '177870249699951'
  FACEBOOK_CLIENT_SECRET: e0af5e79ae086b1bcdd0986eb97e85ca
  LINKEDIN_CLIENT_ID: 81lowl6c00vdya
  LINKEDIN_CLIENT_SECRET: 5Cx8btdS5eNItgw3
  GITHUB_CLIENT_ID: 3973ea2e129b86d94482
  GITHUB_CLIENT_SECRET: da044faf1715ebb45364293ed977d73e90e27c9b
  TWITTER_CLIENT_ID: fWeXTqHOmexRR6SbWy91mAef7
  TWITTER_CLIENT_SECRET: kgsqERWf8xxMPm5ShwTx3rkk6ZSsprIYC9m22uBQBnJa0VC7Os
  INSTAGRAM_CLIENT_ID: 204a84d056b847ffafdc2b23d8757b08
  INSTAGRAM_CLIENT_SECRET: 41983fa70597483b81356a781559fd64
production:
  AUTH_SECRET: blahblah!
  GOOGLE_CLIENT_ID: 586067862296-pttgljei109ujalg8kumqiepop4tdo2a.apps.googleusercontent.com
  GOOGLE_CLIENT_SECRET: ug7mg7n_RUG8wxQIz-pRHcZz
  FACEBOOK_CLIENT_ID: '177870249699951'
  FACEBOOK_CLIENT_SECRET: e0af5e79ae086b1bcdd0986eb97e85ca
  LINKEDIN_CLIENT_ID: 81lowl6c00vdya
  LINKEDIN_CLIENT_SECRET: 5Cx8btdS5eNItgw3
  GITHUB_CLIENT_ID: Iv1.f2463af20727ae0f
  GITHUB_CLIENT_SECRET: 901ea4193ddc1ee99550748c1f32819fea23b86f
  TWITTER_CLIENT_ID: t0KVMOMzaP62EDXwPG51wgu3M
  TWITTER_CLIENT_SECRET: jXXchox8Ur5QG6DmTe562MbrgJF1nHy7bPPrMBPKyfGIh63w6e
  INSTAGRAM_CLIENT_ID: 204a84d056b847ffafdc2b23d8757b08
  INSTAGRAM_CLIENT_SECRET: 41983fa70597483b81356a781559fd64
